- name: Using a role to deploy a webservice
  hosts: web
  gather_facts: no
  become: yes
  
  #roles:
  # - alta3.webservice
  
  tasks:
          - name: Buile a webserver
            import_role: 
            - name: alta3.webservice
         
